### PR TITLE
Added Responsiveness for mobile

### LINKED ISSUE #1: Site is not mobile responsive
Currently, the site is not well optimized for mobile view ports. 

image

### PR DESCRIPTION
**Pull request by Vaishali785**
Added a file called mobile_styles.css for mobile responsive site

Fixes #1

### CODE REVIEW

**Comment by gaurav-saiteja** [comment]
This branch doesn't seem to work. Did you test this code before submitting a pull request?

**Comment by Vaishali785** [comment]
> This branch doesn't seem to work. Did you test this code before submitting a pull request?

Ofcourse, I did. There were some issues in the main code, maybe for my system only. So I fixed them, did all the changes and undo those fixes. You can see here it is working and it is responsive.

Screenshot 2023-10-01 at 1 22 58 PM

**Comment by gaurav-saiteja** [comment]
Yes, I was referring to the gradient box in the title. I had the issue on my side too

**Comment by Vaishali785** [comment]
> Yes, I was referring to the gradient box in the title. I had the issue on my side too

Actually that's not what my issue was. My issues were: 
1. First was related to js file. It was causing some error due to which fetch button was not working.
2. Second issue was "Cannot use import statement outside a module".

By the way, I've fixed gradient issue also.

Screenshot 2023-10-01 at 1 37 46 PM

**Comment by gaurav-saiteja** [comment]
Ok can you create a new pull request with all these changes once again?

**Comment by Vaishali785** [comment]
> Ok can you create a new pull request with all these changes once again?

I've added these changes here only. Should I still create another PR?

**Comment by gaurav-saiteja** [comment]
Yes.

**Comment by Vaishali785** [comment]
Creating a new PR with same code

**Pull request closed without merging**
