### PR TITLE
Added Responsiveness for mobile 

### LINKED ISSUE #1: Site is not mobile responsive
Currently, the site is not well optimized for mobile view ports. 

image

### PR DESCRIPTION
**Pull request by Vaishali785**
Added a file called mobile_styles.css for mobile responsive site

Fixes #1 
Screenshot 2023-10-01 at 1 37 46 PM

### CODE REVIEW

**Comment by gaurav-saiteja** [comment]
Thanks for all your commits. Your request is merged

**Comment by gaurav-saiteja** [comment]
By the way, you seem interested in JavaScript. Any way to contact you?

**Comment by Vaishali785** [comment]
> Thanks for all your commits. Your request is merged

Thanks for merging my PR.

**Comment by Vaishali785** [comment]
Yes I'm interested in JS as I'm a frontend developer. You can connect with
me on my LinkedIn - linkedIn.com/in/vaishali-aggarwal-react-developer

**Pull request merged**
